<?php
/**
 * @file
 * Code for the Documents feature.
 */

include_once 'hr_documents.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function hr_documents_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_documents';
  $feature->name = t('Documents');
  $feature->description = t('Provide documents to your space.');
  $feature->components = array(
    'node' => array(
      'hr_document',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function hr_documents_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['hr_documents'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['hr_documents'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/documents');
    }
    else {
      // See if menu link already exists
      if (empty(menu_link_get_preferred('node/'.$entity_id.'/documents', OG_MENU_SINGLE_MENU_NAME))) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/documents',
          'link_title' => 'Documents',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 4,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}

